#!/bin/zsh
#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

_zprofile() {
  # export _CONTROL="${_CONTROL}:.zprofile"
  # echo $_CONTROL
}
_zprofile
unset -f _zprofile
