#!/usr/bin/env zsh
#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

function () {
  # export _CONTROL="${_CONTROL}:.zprofile"
  # echo $_CONTROL
}
