#!/bin/zsh
#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

_zshenv() {
  # export _CONTROL="${_CONTROL}:.zshenv"
  # echo $_CONTROL

  if [[ -f "$HOME/.env_common" ]]; then
    source "$HOME/.env_common"
  fi

  #
  # Paths
  #

  # Ensure path arrays do not contain duplicates.
  typeset -gU cdpath fpath mailpath path

  # Ensure that a non-login, non-interactive shell has a defined environment.
  if [[ ("$SHLVL" -eq 1 && ! -o LOGIN) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprofile"
  fi

  if [[ -d "$HOME/.local/bin" ]]; then
    export PATH="$HOME/.local/bin:$PATH"
  fi
}
_zshenv
unset -f _zshenv
