#!/bin/zsh
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

_zshrc() {
  # export _CONTROL="${_CONTROL}:.zshrc"
  # echo $_CONTROL

  local UNAME_RES="$(uname -s)"

  case "$UNAME_RES" in
  Linux) local IS_LINUX="true" ;;
  Darwin) local IS_MAC="true" ;;
  esac

  ###
  # Brew workaround for Apple silicon
  ###

  if [[ "$IS_MAC" == true ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi

  ###
  # PNPM
  ###

  #
  # Managed by nvm plugin
  #
  # case true in
  #   $IS_LINUX) export PNPM_HOME="$HOME/.local/share/pnpm" ;;
  #   $IS_MAC) export PNPM_HOME="$HOME/Library/pnpm" ;;
  # esac

  # case ":$PATH:" in
  #   *":$PNPM_HOME:"*) ;;
  #   *) export PATH="$PNPM_HOME:$PATH" ;;
  # esac

  ###
  # Built-in time util format
  ###

  if [[ "$IS_MAC" == true ]]; then
    local MEMORY_UNITS="KB"
  else
    local MEMORY_UNITS="MB"
  fi

  export TIMEFMT=$'\n%J'$'\n%U  user %S system %P cpu %*E total  %M '$MEMORY_UNITS

  ###
  # SSH agent by gnome-keyring-daemon
  ###

  # if [[ $IS_LINUX == true ]]; then
  #   export SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
  #   export SSH_AUTH_SOCK="$HOME/gcr/ssh"
  # fi

  ###
  # The Fuck
  ###

  # eval `thefuck --alias`

  ###
  # Prezto nvm module options
  ###

  export NVM_LAZY_LOAD=true

  #
  # There is better completion included already
  #
  # export NVM_COMPLETION=true

  export NVM_AUTO_USE=true

  export NVM_AUTO_USE_ON_LOAD=true

  ###
  # Mono
  ###

  # export MONO_GAC_PREFIX="/opt/homebrew"

  ###
  # Custom aliases
  ###

  alias lspath='echo "$PATH" | tr ":" "\n"'

  ucode() {
    printf '0x%X\n' "'$1"
  }

  ###
  # Prezto
  ###

  source "$HOME/.zprezto/init.zsh"

  ###
  # Completion
  ###

  compdef pnpm='npm'

  ###
  # Python related stuff
  ###

  export CLOUDSDK_PYTHON_SITEPACKAGES=1

  ###
  # End
  ###
}
_zshrc
unset -f _zshrc
