#!/usr/bin/env zsh
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Brew workaround for M1
#

if [[ $(uname -m) == 'arm64' ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# export _CONTROL="${_CONTROL}:.zshrc"
# echo $_CONTROL

#
# nvm
#

export NVM_LAZY_LOAD=true

# There is better completion included already
# export NVM_COMPLETION=true

export NVM_AUTO_USE=true

export NVM_AUTO_USE_ON_LOAD=true

#
# Prezto
#

source ~/.zprezto/init.zsh

#
# pnpm
#

export PNPM_HOME="/home/rgp/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

#
# Built-in time util format
#

if [[ `uname` == Darwin ]]; then
  MEMORY_UNITS=KB
else
  MEMORY_UNITS=MB
fi

TIMEFMT=$'\n'\
'%J'$'\n'\
'%U  user %S system %P cpu %*E total  %M '$MEMORY_UNITS

#
# SSH agent by gnome-keyring-daemon
#
export SSH_AUTH_SOCK=/run/user/1000/keyring/ssh

#
# The Fuck
#

# eval $(thefuck --alias)

#
# end
#
