#!/usr/bin/env zsh
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# export _CONTROL="${_CONTROL}:.zshrc"
# echo $_CONTROL

#
# NVM
#

export NVM_LAZY_LOAD=true

# There is better completion included already
# export NVM_COMPLETION=true

export NVM_AUTO_USE=true

export NVM_AUTO_USE_ON_LOAD=true

#
# Prezto
#

source ~/.zprezto/init.zsh
